name: Sharehealth
version: 1.0
main: com.benjocraeft.sharehealth.Sharehealth
api-version: 1.16
authors: [ BenjoCraeft ]
description: This plugin makes all players on the server share their health, if one dies, everybody dies.
website: https://mc.benjocraeft.com

commands:
  sharehealth:
    usage: /<command>
    aliases: [sh]
    description: Defined by ShareHealth plugin